arch: amd64

language: java

jdk:
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2

script:
  - java --version
  - mvn clean package
  - mvn pmd:pmd
  - mvn pmd:check

before_install:
  - chmod +x mvnw